### ISSUE TITLE
getContractDetails should be able to deliver several contracts 

### ISSUE THREAD

**Issue by krambox** [stoqey/ibkr#19]
With getContractDetails it is currently not possible to deliver multiple ContractDetails like an option chain.  

    {
      currency: 'USD',
      exchange: 'SMART',
      //expiry: '202007',
      multiplier: 100,
      right: 'C',
      secType: 'OPT',
      strike: 300,
      symbol: 'AAPL'
    }

Currently this query returns 16 options in the TWS API but getContractDetails returns only one of them.

**Comment by krambox** [comment]
Yes, now get several options. You guys changed that incredibly quickly. But you changed the signature of the method getContractDetails. This is OK for me, but I hope this doesn't cause problems in other places.

**Comment by ceddybi** [comment]
@krambox #21 with this one, you can receive object or array depending on arguments passed,
