### ISSUE TITLE
Missing `chalk` and `dotenv` dependencies

### ISSUE THREAD

**Issue by gjtorikian** [stoqey/ibkr#5]
These modules are listed as dev dependencies, but they're not:

https://github.com/stoqey/ibkr/blob/02a527a35cbe25918ef1a3352ef204c37b1e9e57/src/connection/IBKRConnection.ts#L2

https://github.com/stoqey/ibkr/blob/02a527a35cbe25918ef1a3352ef204c37b1e9e57/src/config.ts#L9-L11

**Comment by ceddybi** [comment]
@gjtorikian Thank you, just updated with `dotenv` and `chalk` as direct dependencies
