### ISSUE TITLE
`comboLegsDescrip` in `ContractObject` should be optional

### ISSUE THREAD

**Issue by ellis** [stoqey/ibkr#54]
Hi there, and thanks for your work on this library!  I was trying it out for saving some of my IB data, and it looks like the `comboLegsDescrip` isn't always present for `ContractObject`s.  Would you be able to make it an option parameter in the interface?

**Comment by ceddybi** [comment]
@ellis Thank you for reporting this, i've just made it optional and some other fields i felt like they were not required, please let me know if there are more fields that should have this, thank you

**Comment by ellis** [comment]
Thanks @ceddybi, looks good to me!
