### ISSUE TITLE
AccountSummary only returns data from 1 account for clients with multiple account IDs

### ISSUE THREAD

**Issue by bayareacoder** [stoqey/ibkr#66]
For clients with multiple accounts (eg separate IRA and brokerage accounts), the `AccountSummary` class will only return data from one of their accounts, when issuing `init` or `getAccountSummary`

Reason:
IBKR callback `accountSummary` is called for each account, yet the result overwrites each time so only the data from the last account will be returned.

eg in `src/account/AccountSummary`:

```
 // Record values from here
        ib.on('accountSummary', (reqId, account, tag, value, currency) => {
            self.tickerId = reqId;
            self.AccountId = account;
            self.accountSummary.AccountId = account;
            self.accountSummary[tag] = value; // set the account value
            self.accountSummary.Currency = currency; // always set the account currency
            // log('accountSummaryEnd', { account, tag, value, });
        });

        // Return values from here
        ib.once('accountSummaryEnd', () => {
            const {AccountId = 'unknown', tickerId, accountReady, accountSummary} = self;

            log('accountSummaryEnd', {AccountId, tickerId, accountReady});

            ib.cancelAccountSummary(tickerId);

            publishDataToTopic({
                topic: IBKREVENTS.ON_ACCOUNT_SUMMARY,
                data: accountSummary,
            });

            self.accountReady = true;
        });
```

Solution: 
make `self.accountSummary` an object with `accountId` as keys. Store data from each `accountSummary` callback under the right key (so adding a [tag] key under that `accountId`). Only resolve promise of `getAccountSummary` or call `publishDataToTopic` after you receive an `accountSummaryEnd` since only then will you have received data from all `accountId`s for the currently logged in user.

Here is a gist with a corrected `AccountSummary.ts`. Note that I also first-letter-lowercased the returned tags to be more JS-style  compliant, so you will need to make some changes to the interface file and some other files also that use `accountId` which has been replaced by `accountIds`. For instance you will need to change Portfolios so it takes an `accountId` as an input so you can return a portfolio per account. 

https://gist.github.com/bayareacoder/0f173afe96f2a601e21d6f581396f739#file-accountsummary-ts

**Comment by ceddybi** [comment]
@bayareacoder thank you very much for pointing this out, 

When we first created this module, we heavily invested in only using one account, case scenarios

- We can update the current code and let it use multiple accounts, but most of the implementations will now require to pass the accountId, e.g getPortfolios, getMarketData .e.t.c

- The current IBKR is outdated, there's a PR https://github.com/stoqey/ibkr/pull/61 to re-do with the newer stable version of IB API https://github.com/stoqey/ib (The original main module)

- We'd be very happy if you help in upgrading this module to a newer IB api or just patching the current version to work nicely with multiple accounts, either way your contributions are highly appreciated 

Thank you

**Comment by ceddybi** [comment]
@bayareacoder Would you mind testing with this https://github.com/stoqey/ibkr/pull/67, I think I just found a way to fix it without re-doing too much, it's actually easier than I thought

Thank you

**Comment by bayareacoder** [comment]
OK. I'll be working on this more over the next week or so, and will send suggested updates after that (I also just wrote #68 for portfolios before I saw your reply).

**Comment by ceddybi** [comment]
I already fixed this https://github.com/stoqey/ibkr/pull/67
